name: Mark notifications for closed PRs as done

on:
  workflow_dispatch:

jobs:
  mark:
    name: Mark notifications for closed PRs as done
    runs-on: ubuntu-latest

    steps:
      - name: Mark notifications for closed PRs as done
        uses: actions/github-script@v7
        id: mark-closed-done
        with:
          github-token: ${{ secrets.GH_TOKEN }} 
          script: |-
            github.paginate("GET /notifications").then(async (notifications) => {
              let modified = 0;
              for (const notification of notifications) {
                if (notification.subject.type === "PullRequest") {
                  const { data: pr } = await github.request(
                    `GET ${new URL(notification.subject.url).pathname}`
                  );
                  if (pr.state === "closed") {
                    await github.request("DELETE /notifications/threads/{thread_id}", {
                      thread_id: notification.id,
                    });

                    modified += 1;
                  }
                }
              }

              await core.summary
                .addRaw(`Marked ${modified} notifications as done`, true)
                .write();
            });
